export * from './LandingPage/HomeScreen'
export * from './Bodegas/Bodegas'
export * from './BodegasDisponibles/BodegasDisponibles'
export * from './Reservation/Reservation'
export * from './PerfilBodegas/PerfilBodegas'
export * from './Register/Register'
export * from './Login/Login'
